name: Scheduled Workflow

on:
  schedule:
    - cron: "45 20 * * *"  # todos os dias às 20:45 UTC
  workflow_dispatch:      # opcional, permite execução manual

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Executando tarefa agendada
        run: echo "Tarefa executada automaticamente"
